"""empty message

Revision ID: 6228fc8790d1
Revises: 015891df3491
Create Date: 2024-08-05 18:57:51.143892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6228fc8790d1'
down_revision = '015891df3491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boulding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bouldingname', sa.String(length=80), nullable=False),
    sa.Column('administrator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['administrator_id'], ['administrator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boulding')
    # ### end Alembic commands ###
