"""empty message

Revision ID: bf61bc1d18a6
Revises: e04e9e49cbfb
Create Date: 2024-08-13 11:30:35.934514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf61bc1d18a6'
down_revision = 'e04e9e49cbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('neighbor', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neighbor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    with op.batch_alter_table('administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=80), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
